# Generated by Django 4.1.2 on 2022-10-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='photos_items/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
