# Generated by Django 4.1.2 on 2022-10-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_name_category_catname_remove_item_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.CreateModel(
            name='Item_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ITALAlternative', models.ManyToManyField(related_name='Item_Alternative', to='product.item')),
                ('ITALName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item_Name', to='product.item')),
            ],
            options={
                'verbose_name': 'Item_Alternative',
                'verbose_name_plural': 'Item_AlternatIives',
            },
        ),
    ]
