# Generated by Django 4.1.2 on 2022-10-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_category_options_alter_category_catparent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ITACCAlternative', models.ManyToManyField(related_name='Item_Accessories', to='product.item')),
                ('ITACCName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item_Name_ACC', to='product.item')),
            ],
            options={
                'verbose_name': 'Item_Accessory',
                'verbose_name_plural': 'Item_Accessories',
            },
        ),
    ]
