# Generated by Django 4.1.2 on 2022-10-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_item_accessories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_accessories',
            options={'verbose_name': 'Item Accessory', 'verbose_name_plural': 'Items Accessories'},
        ),
        migrations.AlterModelOptions(
            name='item_alternative',
            options={'verbose_name': 'Item Alternative', 'verbose_name_plural': 'Items AlternatIives'},
        ),
        migrations.AlterField(
            model_name='category',
            name='CATDesc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImage',
            field=models.ImageField(upload_to='Images_categories/%y/%m/%d', verbose_name='Category Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='item_accessories',
            name='ITACCAlternative',
            field=models.ManyToManyField(related_name='Item_Accessories', to='product.item', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='item_accessories',
            name='ITACCName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item_Name_ACC', to='product.item', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item_alternative',
            name='ITALAlternative',
            field=models.ManyToManyField(related_name='Item_Alternative', to='product.item', verbose_name='Alternatives'),
        ),
        migrations.AlterField(
            model_name='item_alternative',
            name='ITALName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item_Name', to='product.item', verbose_name='Item'),
        ),
    ]
