# Generated by Django 4.1.2 on 2022-10-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_item_brand_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images_items/%y/%m/%d', verbose_name='Product image'),
        ),
    ]
