# Generated by Django 4.1.2 on 2022-10-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_category_catdesc_alter_category_catimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Images_items/22/10/27/download.png', upload_to='Images_items/%y/%m/%d', verbose_name='Product image'),
        ),
    ]
