# Generated by Django 4.1.2 on 2022-10-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount_price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images_items/%y/%m/%d', verbose_name='Product image'),
        ),
    ]
