# Generated by Django 4.1.2 on 2022-10-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_item_discount_price_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discount_price'),
        ),
    ]
