# Generated by Django 4.1.2 on 2022-10-28 12:11

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_country_profile_join_date_profile_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images_profiles/%y/%m/%d', verbose_name='Image')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('location', models.CharField(default='', max_length=100, verbose_name='Location')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_profile', to='accounts.profile', verbose_name='Profile')),
            ],
        ),
    ]
